### ISSUE TITLE
Handle init_existential_value instruction

### ISSUE THREAD

**Issue by bryantam** [uasys/swift#91] opened 2018-07-10 16:57 UTC

**Comment by taufique71** [comment] 2018-07-11 11:02
Duplicate of [Issue 82](https://github.com/themaplelab/swift/issues/82)

**Comment by bryantam** [comment] 2018-07-11 14:24
This is for value, not addr. Are you sure it is a duplicate?

**Comment by taufique71** [comment] 2018-07-12 05:36
Sorry, my mistake.

**Closed as completed** 2018-07-24 18:48 UTC
