### ISSUE TITLE
Handle init_existential_addr instruction

### ISSUE THREAD

**Issue by bryantam** [uasys/swift#90] opened 2018-07-10 16:56 UTC

**Comment by taufique71** [comment] 2018-07-11 11:02
Duplicate of [Issue 82](https://github.com/themaplelab/swift/issues/82)

By the way I created several issues to work on in next few weeks. This (Issue 82) was one of them. But you can take it if you wish.

**Comment by bryantam** [comment] 2018-07-11 14:23
Oops... duplicate again. I should be more careful. Thank you.
I have already finished implementing this and now cleaning up before making a PR. Would you mind closing yours?

**Comment by taufique71** [comment] 2018-07-12 05:34
Sure. Closing [Issue 82](https://github.com/themaplelab/swift/issues/82) then.

**Closed as completed** 2018-07-24 18:28 UTC
